Reactive slacks alert over a threshold value
gridsuite/voltage-init-server pull request #54
Opened 2024-04-02 13:37 UTC by FranckLecuyer

2024-04-10 14:13 UTC, TheMaskedTurtle requested changes
As discussed I'm not convinced by the notification architecture here. We're adding really specific headers, and sending them through a result message. The study-server will just pass them, then we have to define these new headers everywhere. It could be more generic and easier to send a generic event directly to the study-notification-server.

2024-04-11 08:09 UTC, FranckLecuyer commented
> As discussed I'm not convinced by the notification architecture here. We're adding really specific headers, and sending them through a result message. The study-server will just pass them, then we have to define these new headers everywhere. It could be more generic and easier to send a generic event directly to the study-notification-server.

For me, this should be done in another US, to handle also the computation statuses of all computation models.
The notifications must be displayed only for the study concerned, and it's the study-server that actually knows this information ...
Sending event directly to the study-notification-server implies that all the computation servers must have this study uuid ...

2024-04-11 08:49 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/VoltageInitWorkerService.java
> +
Done

2024-04-11 08:49 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/VoltageInitService.java
> +    public static final double DEFAULT_REACTIVE_SLACKS_THRESHOLD = 500.;
Done

2024-04-11 08:49 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/VoltageInitWorkerService.java
> +                }
Done

2024-04-11 08:50 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/VoltageInitWorkerService.java
> +                    Double reactiveSlacksOverThreshold = resultCheckReactiveSlacks != null ? resultCheckReactiveSlacks.getRight() : null;
Done

2024-04-11 14:29 UTC, TheMaskedTurtle approved these changes

2024-04-11 14:29 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/voltageinit/server/service/NotificationService.java
> +    public static final String REACTIVE_SLACKS_OVER_THRESHOLD = "REACTIVE_SLACKS_OVER_THRESHOLD";
This is unused

2024-04-11 15:46 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/NotificationService.java
> +    public static final String REACTIVE_SLACKS_OVER_THRESHOLD = "REACTIVE_SLACKS_OVER_THRESHOLD";
Removed

2024-04-15 12:29 UTC, TheMaskedTurtle approved these changes

2024-04-15 12:29 UTC, TheMaskedTurtle commented on src/main/java/org/gridsuite/voltageinit/server/service/parameters/VoltageInitParametersService.java
> +            .orElse(DEFAULT_REACTIVE_SLACKS_THRESHOLD);
```suggestion
        return Optional.ofNullable(parametersUuid)
            .flatMap(voltageInitParametersRepository::findById)
            .map(VoltageInitParametersEntity::toVoltageInitParametersInfos)
            .map(VoltageInitParametersInfos::getReactiveSlacksThreshold)
            .orElse(DEFAULT_REACTIVE_SLACKS_THRESHOLD);
```

2024-04-15 13:49 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/voltageinit/server/service/parameters/VoltageInitParametersService.java
> +            .orElse(DEFAULT_REACTIVE_SLACKS_THRESHOLD);
Done

2024-04-16 11:17 UTC, merged